New script revriten to functions
Signed-off-by: Martin Zajic <zajca@zajca.(none)>

diff --git a/chap5/bash b/chap5/bash
--- a/chap5/bash
+++ b/chap5/bash
@@ -4,68 +4,64 @@ NAME=bash
 PROGRAM=$NAME-$bash_VER
 FILE=$NAME-$bash_VER$bash_PRIP
 
-source $SCRIPTS_DIR/include/unpack_gzip
+unpackBzip
 
-echo -e "$Y Spoustim Build $DEF"
+waitUser
+
+startBuild
 
 cd $BUILD_DIR/$PROGRAM
 {
-	echo -e "$C Aplikuji patch $DEF"
-	echo -e "$G patch -Np1 -i $SOURCES_DIR/bash-4.1-fixes-2.patch $DEF"
-	patch -Np1 -i patch -Np1 -i $SOURCES_DIR/bash-4.1-fixes-2.patch
+	addPatch bash-4.1-fixes-2.patch
+	
+	waitUser
 
-	echo -e "$G $PROGRAM/configure $DEF" 
-	./configure --prefix=/tools --without-bash-malloc
+	c_Configure --prefix=/tools --without-bash-malloc
 	if [ $? -ne 0 ]
 		then
-			echo -e "$R Configure selhalo $DEF"
+			echo -e "$L_FAIL_CONF"
 			exit 1
 	fi
 
-	echo -e "$G make $DEF"
-	make
+	waitUser
+
+	c_Make
 	if [ $? -ne 0 ]
 		then
-			echo -e "$R make selhalo $DEF"
+			echo -e "$L_FAIL_MAKE"
+			exit 1
+	fi
+
+	waitUser
+	
+	c_MakeTest tests
+	if [ $? -ne 0 ]
+		then
+			echo -e "$L_FAIL_MAKT"
+			exit 1
+	fi
+
+	waitUser
+	
+	c_MakeInstall
+	if [ $? -ne 0 ]
+		then
+			echo -e "$L_FAIL_MAKA"
 			exit 1
 	fi
 	
-	if [ $BUILD_TEST == 1 ] || [ $BUILD_TEST == 3 ];
-    	then
-			echo -e "$G make tests $DEF"
-			make tests
-			if [ $? -ne 0 ]
-				then
-					echo -e "$R make selhalo $DEF"
-					exit 1
-			fi
-	fi
+	waitUser
 	
-	echo -e "$G make-install $DEF"
-	make install
-	if [ $? -ne 0 ]
-		then
-			echo -e "$R make install selhalo $DEF"
-			exit 1
-	fi
-
-	echo -e "$C Vytvarim potrebny symbolicky odkaz $DEF"
-	echo -e "$G ln -vs bash /tools/bin/sh $DEF"
-	ln -vs /tools/bin/bash /tools/bin/sh
+	createSimLink /tools/bin/bash /tools/bin/sh
 } 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
 if [ $PIPESTATUS -ne 0 ]
 	then
-		echo -e "$R build selhal $DEF"
+		echo -e "$L_FAIL_BUIL"
 		exit 1
 fi  	  
-if [ $BUILD_RM == 1 ];
-	then
-		echo -e "$C Mazu slozku se zdrojaky $DEF"
-		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
-		rm -rf $BUILD_DIR/$PROGRAM
 
-	else
-		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
-fi
+waitUser
+
+RMsource
 
 cd $ROOT
diff --git a/chap5/binutilsP2 b/chap5/binutilsP2
--- a/chap5/binutilsP2
+++ b/chap5/binutilsP2
@@ -4,56 +4,62 @@ NAME=binutils
 PROGRAM=$NAME-$binutils_VER
 FILE=$NAME-$binutils_VER$binutils_PRIP
 
-source $SCRIPTS_DIR/include/unpack_sep_bzip
+unpackBzipSep
 
-echo -e "$Y Spoustim Build $DEF"
+waitUser
+
+startBuild
 
 cd $BUILD_DIR/$PROGRAM-BUILD
 echo -e "$G ../$PROGRAM/configure $DEF" 
 {
-CC="$LFS_TGT-gcc -B/tools/lib/" AR=$LFS_TGT-ar RANLIB=$LFS_TGT-ranlib ../$PROGRAM/configure --prefix=/tools --disable-nls --with-lib-path=/tools/lib
+CC="$LFS_TGT-gcc -B/tools/lib/" 
+AR=$LFS_TGT-ar 
+RANLIB=$LFS_TGT-ranlib 
+
+    c_ConfigureSep --prefix=/tools --disable-nls --with-lib-path=/tools/lib
     if [ $? -ne 0 ]
 		then
-			echo -e "$R Configure selhalo $DEF"
+			echo -e "$L_FAIL_CONF"
 			exit 1
 	fi
-    echo -e "$G make $DEF"
-    make 
+    waitUser
+    c_Make
     if [ $? -ne 0 ]
 		then
-			echo -e "$R make selhalo $DEF"
+			echo -e "$L_FAIL_MAKE"
 			exit 1
 	fi
-    echo -e "$G make-install $DEF"
-    make install
+    waitUser
+    c_MakeInstall
     if [ $? -ne 0 ]
 		then
-			echo -e "$R make install selhalo $DEF"
+			echo -e "$L_FAIL_MAKA"
 			exit 1
 	fi 
-    echo -e "$C Priprava linkeru pro dalsi oddeleni v dalsim scriptu $DEF"
-    echo -e "$G make -C ld clean $DEF"
-    make -C ld clean
-    echo -e "$G make -C ld LIB_PATH=/usr/lib:/lib $DEF"
-    make -C ld LIB_PATH=/usr/lib:/lib
-    echo -e "$G cp -v ld/ld-new /tools/bin $DEF"
-    cp -v ld/ld-new /tools/bin
-    sleep 10
+    waitUser
+    c_Make -C ld clean
+    if [ $? -ne 0 ]
+		then
+			echo -e "$L_FAIL_MAKE"
+			exit 1
+    fi
+    waitUser
+    c_Make -C ld LIB_PATH=/usr/lib:/lib
+    if [ $? -ne 0 ]
+		then
+			echo -e "$L_FAIL_MAKE"
+			exit 1
+    fi
+
+    copyFiles ld/ld-new /tools/bin
+
 } 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM-P2.log
 	if [ $PIPESTATUS -ne 0 ]
 		then
-			echo -e "$R build selhal $DEF"
+			echo -e "$L_FAIL_BUIL"
 			exit 1
 	fi  	  
-if [ $BUILD_RM == 1 ];
-	then
-                echo -e "$C Mazu slozku s buildem $DEF"
-                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM-BUILD $DEF"
-                rm -rf $BUILD_DIR/$PROGRAM-BUILD
-                echo -e "$C Mazu slozku se zdrojaky $DEF"
-                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
-                rm -rf $BUILD_DIR/$PROGRAM
-	else
-		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
-fi
+waitUser
+RMbuild
 cd $ROOT
diff --git a/chap5/coreutils b/chap5/coreutils
--- a/chap5/coreutils
+++ b/chap5/coreutils
@@ -4,63 +4,51 @@ NAME=coreutils
 PROGRAM=$NAME-$coreutils_VER
 FILE=$NAME-$coreutils_VER$coreutils_PRIP
 
-source $SCRIPTS_DIR/include/unpack_gzip
+unpackGzip
 
-echo -e "$Y Spoustim Build $DEF"
+waitUser
+
+startBuild
 
 cd $BUILD_DIR/$PROGRAM
 {
-	echo -e "$G $PROGRAM/configure $DEF" 
-	./configure --prefix=/tools --enable-install-program=hostname
+	c_Configure --prefix=/tools --enable-install-program=hostname
 	if [ $? -ne 0 ]
 		then
-			echo -e "$R Configure selhalo $DEF"
+			echo -e "$L_FAIL_CONF"
 			exit 1
 	fi
-
-	echo -e "$G make $DEF"
-	make
+	waitUser
+	c_Make
 	if [ $? -ne 0 ]
 		then
-			echo -e "$R make selhalo $DEF"
+			echo -e "$L_FAIL_MAKE"
 			exit 1
+	fi
+	waitUser
+	c_MakeTest RUN_EXPENSIVE_TESTS=yes check
+	  if [ $? -ne 0 ]
+	    then
+		echo -e "$R make RUN_EXPENSIVE_TESTS=yes check selhalo $DEF"
+		exit 1
 	fi
 	
-	if [ $BUILD_TEST == 1 ] || [ $BUILD_TEST == 3 ];
-    	then
-			echo -e "$G make RUN_EXPENSIVE_TESTS=yes check $DEF"
-			make RUN_EXPENSIVE_TESTS=yes check
-			if [ $? -ne 0 ]
-				then
-					echo -e "$R make RUN_EXPENSIVE_TESTS=yes check selhalo $DEF"
-					exit 1
-			fi
-	fi
-	
-	echo -e "$G make-install $DEF"
-	make install
+	waitUser
+	c_MakeInstall
 	if [ $? -ne 0 ]
 		then
-			echo -e "$R make install selhalo $DEF"
+			echo -e "$L_FAIL_MAKA"
 			exit 1
 	fi
-
-	echo -e "$C Kpoiruji potrebne soubory $DEF"
-	echo -e "$G cp -v src/su /tools/bin/su-tools $DEF"
-	cp -v src/su /tools/bin/su-tools
+	waitUser
+	copyFiles src/su /tools/bin/su-tools
 } 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
 if [ $PIPESTATUS -ne 0 ]
 	then
-		echo -e "$R build selhal $DEF"
+		echo -e "$L_FAIL_BUIL"
 		exit 1
 fi  	
-if [ $BUILD_RM == 1 ];
-	then
-		echo -e "$C Mazu slozku se zdrojaky $DEF"
-		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
-		rm -rf $BUILD_DIR/$PROGRAM
-	else
-		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
-fi
 
+waitUser
+RMsource
 cd $ROOT
diff --git a/chap5/gccP2 b/chap5/gccP2
--- a/chap5/gccP2
+++ b/chap5/gccP2
@@ -3,11 +3,11 @@
 NAME=mpfr
 PROGRAM=$NAME-$mpfr_VER
 FILE=$NAME-$mpfr_VER$mpfr_PRIP
-echo -e "$Y Spousti se rozbaleni programu $PROGRAM $DEF"
+echo -e "$L_START_UNPACK $PROGRAM $DEF"
 
 if [ -d $BUILD_DIR/$PROGRAM ];
 	then
-		echo -e "$C Slozka existuje mazu $DEF"
+		echo -e "$L_RM_ASDIR"
 		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
 		rm -rf $BUILD_DIR/$PROGRAM
 	else
@@ -16,17 +16,17 @@ fi
 
 if [ -d $BUILD_DIR/$NAME ];
 	then
-		echo -e "$C Slozka existuje mazu $DEF"
+		echo -e "$L_RM_ASDIR"
 		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
 		rm -rf $BUILD_DIR/$NAME
 	else
 		echo -e "$M.$DEF"
 fi
 
-echo -e "$C Rozbaluji soubory $DEF"
+echo -e "$L_UN_SDIR"
 echo -e "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
 tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
-echo -e "$C Presunuju soubory pro potreby GCC $DEF"
+echo -e "$L_MV_FILGCC"
 echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
 mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME
 
@@ -35,11 +35,11 @@ cd $ROOT
 NAME=gmp
 PROGRAM=$NAME-$gmp_VER
 FILE=$NAME-$gmp_VER$gmp_PRIP
-echo -e "$Y Spousti se rozbaleni programu $PROGRAM $DEF"
+echo -e "$L_START_UNPACK $PROGRAM $DEF"
 
 if [ -d $BUILD_DIR/$PROGRAM ];
 	then
-		echo -e "$C Slozka existuje mazu $DEF"
+		echo -e "$L_RM_ASDIR"
 		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
 		rm -rf $BUILD_DIR/$PROGRAM
 	else
@@ -48,17 +48,17 @@ fi
 
 if [ -d $BUILD_DIR/$NAME ];
 	then
-		echo -e "$C Slozka existuje mazu $DEF"
+		echo -e "$L_RM_ASDIR"
 		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
 		rm -rf $BUILD_DIR/$NAME
 	else
 		echo -e "$M.$DEF"
 fi
 
-echo -e "$C Rozbaluji soubory $DEF"
+echo -e "$L_UN_SDIR"
 echo -e "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
 tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
-echo -e "$C Presunuju soubory pro potreby GCC $DEF"
+echo -e "$L_MV_FILGCC"
 echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
 mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME
 
@@ -67,11 +67,11 @@ cd $ROOT
 NAME=mpc
 PROGRAM=$NAME-$mpc_VER
 FILE=$NAME-$mpc_VER$mpc_PRIP
-echo -e "$Y Spousti se rozbaleni programu $PROGRAM $DEF"
+echo -e "$L_START_UNPACK $PROGRAM $DEF"
 
 if [ -d $BUILD_DIR/$PROGRAM ];
 	then
-		echo -e "$C Slozka existuje mazu $DEF"
+		echo -e "$L_RM_ASDIR"
 		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
 		rm -rf $BUILD_DIR/$PROGRAM
 	else
@@ -80,17 +80,17 @@ fi
 
 if [ -d $BUILD_DIR/$NAME ];
 	then
-		echo -e "$C Slozka existuje mazu $DEF"
+		echo -e "$L_RM_ASDIR"
 		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
 		rm -rf $BUILD_DIR/$NAME
 	else
 		echo -e "$M.$DEF"
 fi
 
-echo -e "$C Rozbaluji soubory $DEF"
+echo -e "$L_UN_SDIR"
 echo -e "$G tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
 tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/
-echo -e "$C Presunuju soubory pro potreby GCC $DEF"
+echo -e "$L_MV_FILGCC"
 echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
 mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME
 
@@ -100,22 +100,23 @@ NAME=gcc
 PROGRAM=$NAME-$gcc_VER
 FILE=$NAME-$gcc_VER$gcc_PRIP
 
-source $SCRIPTS_DIR/include/unpack_sep_bzip
+unpackBzipSep
 
-cp -rv $BUILD_DIR/gmp $BUILD_DIR/mpc $BUILD_DIR/mpfr $BUILD_DIR/$PROGRAM
+waitUser
+
+startBuild
+
 {
 cd $BUILD_DIR/$PROGRAM
 
-echo -e "$C Aplikuji patch $DEF"
-echo -e "$G patch -Np1 -i $SOURCES_DIR/gcc-4.5.1-startfiles_fix-1.patch $DEF"
-patch -Np1 -i $SOURCES_DIR/gcc-4.5.1-startfiles_fix-1.patch
+addPatch gcc-4.5.1-startfiles_fix-1.patch
 
 cp -v gcc/Makefile.in{,.orig}
 sed 's@\./fixinc\.sh@-c true@' gcc/Makefile.in.orig > gcc/Makefile.in
-
+waitUser
 cp -v gcc/Makefile.in{,.tmp}
 sed 's/^T_CFLAGS =$/& -fomit-frame-pointer/' gcc/Makefile.in.tmp > gcc/Makefile.in
-
+waitUser
 for file in \
  $(find gcc/config -name linux64.h -o -name linux.h -o -name sysv4.h)
 do
@@ -129,77 +130,59 @@ do
 #define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
   touch $file.orig
 done
-
+waitUser
 case $(uname -m) in
   x86_64)
     for file in $(find gcc/config -name t-linux64) ; do \
       cp -v $file{,.orig}
       sed '/MULTILIB_OSDIRNAMES/d' $file.orig > $file
     done
+    waitUser
   ;;
 esac
 
-echo -e "$Y Spoustim Build $DEF"
-
-cd $BUILD_DIR/$PROGRAM-BUILD
-echo -e "$G ../$PROGRAM/configure $DEF" 
-CC="$LFS_TGT-gcc -B/tools/lib/" \
-    AR=$LFS_TGT-ar RANLIB=$LFS_TGT-ranlib \
-    ../gcc-4.5.1/configure --prefix=/tools \
-    --with-local-prefix=/tools --enable-clocale=gnu \
-    --enable-shared --enable-threads=posix \
-    --enable-__cxa_atexit --enable-languages=c,c++ \
-    --disable-libstdcxx-pch --disable-multilib \
-    --disable-bootstrap --disable-libgomp \
-    --with-gmp-include=$(pwd)/gmp --with-gmp-lib=$(pwd)/gmp/.libs \
-    --without-ppl --without-cloog
-	if [ $? -ne 0 ]
+CC="$LFS_TGT-gcc -B/tools/lib/" 
+AR=$LFS_TGT-ar 
+RANLIB=$LFS_TGT-ranlib 
+    c_ConfigureSep --prefix=/tools --with-local-prefix=/tools --enable-clocale=gnu --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-languages=c,c++ --disable-libstdcxx-pch --disable-multilib --disable-bootstrap --disable-libgomp --with-gmp-include=$(pwd)/gmp --with-gmp-lib=$(pwd)/gmp/.libs --without-ppl --without-cloog
+    if [ $? -ne 0 ]
 		then
-			echo -e "$R Configure selhalo $DEF"
+			echo -e "$L_FAIL_CONF"
 			exit 1
 	fi
-	echo -e "$G make $DEF"
-	make
+	waitUser
+	c_Make
 	if [ $? -ne 0 ]
 		then
-			echo -e "$R make selhalo $DEF"
+			echo -e "$L_FAIL_MAKE"
 			exit 1
 	fi
-	echo -e "$G make-install $DEF"
-	make install
+	waitUser
+	c_MakeInstall
 	if [ $? -ne 0 ]
 		then
-			echo -e "$R make install selhalo $DEF"
+			echo -e "$L_FAIL_MAKA"
 			exit 1
 	fi
-
+	waitUser
 	ln -vs gcc /tools/bin/cc
 
 } 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM-P2.log
 if [ $PIPESTATUS -ne 0 ]
 	then
-		echo -e "$R build selhal $DEF"
+		echo -e "$L_FAIL_BUIL"
 		exit 1
 fi  
 
-if [ $BUILD_RM == 1 ];
-	then
-                echo -e "$C Mazu slozku s buildem $DEF"
-                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM-BUILD $DEF"
-                rm -rf $BUILD_DIR/$PROGRAM-BUILD
-                echo -e "$C Mazu slozku se zdrojaky $DEF"
-                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
-                rm -rf $BUILD_DIR/$PROGRAM
-                echo -e "$C Mazu slozku se zdrojaky ke gmp $DEF"
-                echo -e "$G rm -rf $BUILD_DIR/gmp $DEF"
-                rm -rf $BUILD_DIR/gmp
-                echo -e "$C Mazu slozku se zdrojaky mpfr $DEF"
-                echo -e "$G rm -rf $BUILD_DIR/mpfr $DEF"
-                rm -rf $BUILD_DIR/mpfr
-		echo -e "$C Mazu slozku se zdrojaky mpc $DEF"
-		echo -e "$G rm -rf $BUILD_DIR/mpc $DEF"
-		rm -rf $BUILD_DIR/mpc
-	else
-		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
-fi
+waitUser
+RMbuild
+echo -e "$L_RM_SDIR gmp"
+echo -e "$G rm -rf $BUILD_DIR/gmp $DEF"
+rm -rf $BUILD_DIR/gmp
+echo -e "$L_RM_SDIR mpfr"
+echo -e "$G rm -rf $BUILD_DIR/mpfr $DEF"
+rm -rf $BUILD_DIR/mpfr
+echo -e "$L_RM_SDIR mpc"
+echo -e "$G rm -rf $BUILD_DIR/mpc $DEF"
+rm -rf $BUILD_DIR/mpc
 cd $ROOT
diff --git a/chap5/linker b/chap5/linker
--- a/chap5/linker
+++ b/chap5/linker
@@ -1,39 +1,35 @@
 #!/bin/bash
 
-echo -e "$Y Oddeleni Toolchainu $DEF"
+echo -e "$L_START_TOOLCH"
 
-echo -e "$C Nastavuji linker $DEF"
+echo -e "$L_SET_LINK"
 cd $TOOLS_DIR
 {
 SPECS=`dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/specs
 $LFS_TGT-gcc -dumpspecs | sed -e 's@/lib\(64\)\?/ld@/tools&@g' -e "/^\*cpp:$/{n;s,$, -isystem /tools/include,}" > $SPECS
-echo "Nový specs soubor je: $SPECS"
+echo "New specs: $SPECS"
 unset SPECS
 
 
-echo -e "$Y Testuju spravnost $DEF"
+echo -e "$L_TEST_SPR"
 
 echo 'main(){}' > dummy.c
 $LFS_TGT-gcc -B/tools/lib dummy.c
 
 readelf -l a.out | grep ': /tools' > testlink.1
 
-if cmp $SCRIPTS_DIR/linker.1.test $TOOLS_DIR/testlink.1 &> /dev/null
-	then
-		echo -e "$C Linker test $G [OK] $DEF"
-	else
-		echo -e "$C Linker test $R [FAIL] $DEF"
-		echo -e "$R Je treba uzivatelske interakce [Prerusuji] $DEF"
-		exit 1
-fi
+case $(uname -m) in
+    x86_64) compareFiles $SCRIPTS_DIR/linker.1.test64 $TOOLS_DIR/testlink.1 ;;
+    i?86) compareFiles cmp $SCRIPTS_DIR/linker.1.test $TOOLS_DIR/testlink.1 ;; 
+esac
 } 2>&1 | tee $BUILD_DIR/LOG_LINKER.log
-if cmp $SCRIPTS_DIR/linker.1.test $TOOLS_DIR/testlink.1 &> /dev/null
+if [ $PIPESTATUS -ne 0 ]
 	then
-		echo -e "$C . $DEF"
-	else
+		echo -e "$L_FAIL_BUIL"
 		exit 1
-fi
-echo -e "$C Mazu docasne soubory $DEF $G /tools/dummy.c, /tools/a.out $DEF"
+fi  
+
+echo -e "$L_RM_TFIL $G /tools/dummy.c, /tools/a.out $DEF"
 rm -r $TOOLS_DIR/dummy.c $TOOLS_DIR/a.out
-echo -e "$C Pro kontrolu je nechan soubor $DEF $G $TOOLS_DIR/testlink.1 $DEF"
+echo -e "$DEF $G $TOOLS_DIR/testlink.1 $DEF $L_SET_KEEP"
 cd $ROOT
diff --git a/chap5/linkerP2 b/chap5/linkerP2
--- a/chap5/linkerP2
+++ b/chap5/linkerP2
@@ -1,8 +1,6 @@
 #!/bin/bash
 
-echo -e "$Y Test kompilatoru $DEF"
-
-echo -e "$C Testuju spravnost $DEF"
+echo -e "$L_TEST_SPR"
 cd $TOOLS_DIR
 {
 echo 'main(){}' > dummy.c
@@ -10,24 +8,18 @@ cc dummy.c
 
 readelf -l a.out | grep ': /tools' > testlink.2
 
-if cmp $SCRIPTS_DIR/linker.1.test $TOOLS_DIR/testlink.2 &> /dev/null
+case $(uname -m) in
+    x86_64) compareFiles $SCRIPTS_DIR/linker.1.test64 $TOOLS_DIR/testlink.2 ;;
+    i?86) compareFiles $SCRIPTS_DIR/linker.1.test $TOOLS_DIR/testlink.2 ;; 
+esac
+if [ $PIPESTATUS -ne 0 ]
 	then
-		echo -e "$C Linker test $G [OK] $DEF"
-	else
-		echo -e "$C Linker test $R [FAIL] $DEF"
-		echo -e "$R Je treba uzivatelske interakce [Prerusuji] $DEF"
+		echo -e "$L_FAIL_BUIL"
 		exit 1
-fi
-} 2>&1 | tee $BUILD_DIR/LOG_LINKER-P2.log
+fi  
 
-if cmp $SCRIPTS_DIR/linker.1.test $TOOLS_DIR/testlink.2 &> /dev/null
-	then
-		echo -e "$C . $DEF"
-	else
-		exit 1
-fi
-echo -e "$C Mazu docasne soubory $DEF $G /tools/dummy.c, /tools/a.out $DEF"
+echo -e "$L_RM_TFIL $DEF $G /tools/dummy.c, /tools/a.out $DEF"
 rm -r $TOOLS_DIR/dummy.c $TOOLS_DIR/a.out
-echo -e "$C Pro kontrolu je nechan soubor $DEF $G $TOOLS_DIR/testlink.2 $DEF"
+echo -e "$G $TOOLS_DIR/testlink.2 $DEF $L_SET_KEEP"
 
 cd $ROOT
diff --git a/chap5/tcl b/chap5/tcl
--- a/chap5/tcl
+++ b/chap5/tcl
@@ -4,71 +4,62 @@ NAME=tcl
 PROGRAM=$NAME$tcl_VER2
 FILE=$NAME$tcl_VER$tcl_PRIP
 
-source $SCRIPTS_DIR/include/unpack_gzip
+unpackGzip
 
-echo -e "$Y Spoustim Build $DEF"
+waitUser
+
+startBuild
 {
 cd $BUILD_DIR/$PROGRAM/unix
-	echo -e "$G $PROGRAM/configure $DEF" 
-    ./configure --prefix=/tools
+    
+    c_Configure --prefix=/tools
     if [ $? -ne 0 ]
 		then
-			echo -e "$R Configure selhalo $DEF"
+			echo -e "$L_FAIL_CONF"
 			exit 1
 	fi
-
-    echo -e "$G make $DEF"
-    make
+    waitUser
+    c_Make
     if [ $? -ne 0 ]
 		then
-			echo -e "$R make selhalo $DEF"
+			echo -e "$L_FAIL_MAKE"
 			exit 1
 	fi
-	
-	if [ $BUILD_TEST == 1 ] || [ $BUILD_TEST == 3 ];
-		then
-	    echo -e "$G make test $DEF"
-	    TZ=UTC make test
-	    if [ $? -ne 0 ]
-			then
-				echo -e "$R make selhalo $DEF"
-				exit 1
-		fi
+	waitUser
+	TZ=UTC
+	c_Make test
+	if [ $? -ne 0 ]
+	  then
+	      echo -e "$L_FAIL_MAKT"
+	      exit 1
 	fi
-	
-    echo -e "$G make-install $DEF"
-    make install
-    if [ $? -ne 0 ]
+	waitUser
+	c_MakeInstall
+	if [ $? -ne 0 ]
 		then
-			echo -e "$R make install selhalo $DEF"
+			echo -e "$L_FAIL_MAKA"
 			exit 1
 	fi
-	echo -e "$C menim prava $G /tools/lib/libtcl8.5.so $DEF"
+	waitUser
+	echo -e "$L_CH_PRI $G /tools/lib/libtcl8.5.so $DEF"
 	echo -e "$G chmod -v u+w /tools/lib/libtcl8.5.so $DEF"
 	chmod -v u+w /tools/lib/libtcl8.5.so
-	
-	echo -e "$G make install-private-headers $DEF"
-    make install-private-headers
-    if [ $? -ne 0 ]
+	waitUser
+	c_Make install-private-headers
+	if [ $? -ne 0 ]
 		then
-			echo -e "$R make install selhalo $DEF"
+			echo -e "$L_FAIL_MAKT $R install-private-headers $DEF"
 			exit 1
 	fi
-	echo -e "$C Vytvarim potrebny symbolicky odkaz $DEF"
+	echo -e "$L_MK_LNS"
 	echo -e "$G ln -sv tclsh8.5 /tools/bin/tclsh $DEF"
 	ln -sv tclsh8.5 /tools/bin/tclsh
 } 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
 if [ $PIPESTATUS -ne 0 ]
 	then
-		echo -e "$R build selhal $DEF"
+		echo -e "$L_FAIL_BUIL"
 		exit 1
 fi  
-if [ $BUILD_RM == 1 ];
-	then
-		echo -e "$C Mazu slozku se zdrojaky $DEF"
-		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
-		rm -rf $BUILD_DIR/$PROGRAM
-	else
-		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
-fi
+waitUser
+RMsource
 cd $ROOT
