Updated to LFS 6.8
few functions were added

diff --git a/chap5/binutils b/chap5/binutils
--- a/chap5/binutils
+++ b/chap5/binutils
@@ -1,11 +1,26 @@
 #!/bin/bash
 
-NAME=binutils
-PROGRAM=$NAME-$binutils_VER
-FILE=$NAME-$binutils_VER$binutils_PRIP
+NAME=${binutils[0]}
+PROGRAM=${binutils[3]}
+FILE=${binutils[2]}
+EXT=${binutils[4]}
+DLINK=${binutils[1]}
+MD5=${binutils[5]}
 TIMEFORMAT="%1R = 1 SBU - $PROGRAM"
 
-unpackBzipSep
+download ${DLINK}
+
+waitUser
+
+check ${FILE} ${MD5}
+
+waitUser
+
+unpack ${EXT}
+
+waitUser
+
+SepBuild
 
 waitUser
 
@@ -15,21 +30,21 @@ cd $BUILD_DIR/$PROGRAM-BUILD
 
 { time \
   {
-
-    c_ConfigureSep --target=$LFS_TGT --prefix=/tools --disable-nls --disable-werror || exit 1
+	echo "$G ../$PROGRAM/configure --target=$LFS_TGT --prefix=/tools --disable-nls --disable-werror $DEF" 
+    ../$PROGRAM/configure --target=$LFS_TGT --prefix=/tools --disable-nls --disable-werror || exit 1
 
     waitUser
-
+    echo "$G make $DEF"
     c_Make || exit 1
 
     waitUser
 
     case $(uname -m) in
-    x86_64) mkdir -v /tools/lib && ln -sv lib /tools/lib64 ;;
+      x86_64) mkdir -v /tools/lib && ln -sv lib /tools/lib64 ;;
     esac
-    
-    waitUser
 
+    waitUser
+    echo "$G make isntall $DEF"
     c_MakeInstall || exit 1
   }
 } 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
diff --git a/chap5/binutilsP2 b/chap5/binutilsP2
--- a/chap5/binutilsP2
+++ b/chap5/binutilsP2
@@ -1,31 +1,53 @@
 #!/bin/bash
 
-NAME=binutils
-PROGRAM=$NAME-$binutils_VER
-FILE=$NAME-$binutils_VER$binutils_PRIP
+NAME=${binutils[0]}
+PROGRAM=${binutils[3]}
+FILE=${binutils[2]}
+EXT=${binutils[4]}
+DLINK=${binutils[1]}
+MD5=${binutils[5]}
 
-unpackBzipSep
+download ${DLINK}
+
+waitUser
+
+check ${FILE} ${MD5}
+
+waitUser
+
+unpack ${EXT}
+
+waitUser
+
+SepBuild
 
 waitUser
 
 startBuild
 
 cd $BUILD_DIR/$PROGRAM-BUILD
-echo -e "$G ../$PROGRAM/configure $DEF" 
 {
-CC="$LFS_TGT-gcc -B/tools/lib/" 
-AR=$LFS_TGT-ar 
-RANLIB=$LFS_TGT-ranlib 
 
-    c_ConfigureSep --prefix=/tools --disable-nls --with-lib-path=/tools/lib || exit 1
+echo "$G ../$PROGRAM/configure --prefix=/tools --disable-nls --with-lib-path=/tools/lib $DEF" 
+CC="$LFS_TGT-gcc -B/tools/lib/" AR=$LFS_TGT-ar RANLIB=$LFS_TGT-ranlib ../$PROGRAM/configure --prefix=/tools --disable-nls --with-lib-path=/tools/lib
+    if [ $? -ne 0 ]
+		then
+			echo -e "$L_FAIL_MAKE"
+			exit 1
+    fi
+
     waitUser
-    c_Make || exit 1
+    echo "$G make $DEF" 
+    make || exit 1
     waitUser
-    c_MakeInstall || exit 1
+    echo "$G make install $DEF" 
+    make install || exit 1
     waitUser
-    c_Make -C ld clean || exit 1
+    echo "$G make -C ld clean $DEF" 
+    make -C ld clean || exit 1
     waitUser
-    c_Make -C ld LIB_PATH=/usr/lib:/lib
+    echo "$G make -C ld LIB_PATH=/usr/lib:/lib $DEF"
+    make -C ld LIB_PATH=/usr/lib:/lib
     if [ $? -ne 0 ]
 		then
 			echo -e "$L_FAIL_MAKE"
diff --git a/include/functions b/include/functions
--- a/include/functions
+++ b/include/functions
@@ -14,22 +14,35 @@ startBuild (){
 }
 export -f startBuild
 
+# function chose what to be done with archive
+# parametr 1 file extension bzip or gzip
+# ordionary use unpack ${EXT}
+unpack(){
+if [ $1 == bzip ]; then
+      unpackBzip
+  elif [ $1 == gzip ]; then
+      unpackGzip
+  else
+    echo "$R somethink went wrong with archive unpack $DEF";
+fi
+}
+export -f unpack
+
 #Function unpacking archive
 unpackBzip (){
 	echo "$Y Starting build script $PROGRAM $DEF";
 
-	if [ -d $BUILD_DIR/$PROGRAM ];
-		then
-			echo "$C Directory with source already exist $G [REMOVING] $DEF"
-			echo "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
-			rm -rf $BUILD_DIR/$PROGRAM
-			echo "$C Source directory $G [UNPACKING] $DEF"
-			echo "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
-			tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
-		else
-			echo "$C Source directory $G [UNPACKING] $DEF"
-			echo "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
-			tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
+	if [ -d $BUILD_DIR/$PROGRAM ]; then
+	  echo "$C Directory with source already exist $G [REMOVING] $DEF"
+	  echo "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
+	  rm -rf $BUILD_DIR/$PROGRAM
+	  echo "$C Source directory $G [UNPACKING] $DEF"
+	  echo "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
+	  tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
+	else
+	  echo "$C Source directory $G [UNPACKING] $DEF"
+	  echo "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
+	  tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
 	fi
 }
 export -f unpackBzip
@@ -38,98 +51,67 @@ export -f unpackBzip
 unpackGzip (){
 	echo "$Y Starting build script $PROGRAM $DEF";
 
-	if [ -d $BUILD_DIR/$PROGRAM ];
-		then
-			echo "$C Directory with source already exist $G [REMOVING] $DEF"
-			echo "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
-			rm -rf $BUILD_DIR/$PROGRAM
-			echo "$C Source directory $G [UNPACKING] $DEF"
-			echo "$G tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
-			tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/
-		else
-			echo "$C Source directory $G [UNPACKING] $DEF"
-			echo "$G tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
-			tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/
+	if [ -d $BUILD_DIR/$PROGRAM ]; then
+	  echo "$C Directory with source already exist $G [REMOVING] $DEF"
+	  echo "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
+	  rm -rf $BUILD_DIR/$PROGRAM
+	  echo "$C Source directory $G [UNPACKING] $DEF"
+	  echo "$G tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
+	  tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/
+	else
+	  echo "$C Source directory $G [UNPACKING] $DEF"
+	  echo "$G tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
+	  tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/
 	fi
 }
 export -f unpackGzip
 
-#Function unpacking archive and make directory for separete build
-unpackGzipSep (){
-	echo "$Y Starting build script $PROGRAM $DEF";
+#Function for prepare to separate build
+SepBuild (){
+	echo "$Y Preparing for separate build $PROGRAM $DEF";
 
-	if [ -d $BUILD_DIR/$PROGRAM ];
-		then
-			echo "$C Directory with source already exist $G [REMOVING] $DEF"
-			echo "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
-			rm -rf $BUILD_DIR/$PROGRAM
-			echo "$C Source direcotry $G [UNPACKING] $DEF"
-			echo "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
-			tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/
-		else
-			echo "$C Source direcotry $G [UNPACKING] $DEF"
-			echo "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
-			tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/
-	fi
-
-	if [ -d $BUILD_DIR/$PROGRAM-BUILD ];
-		then
-			echo "$C Build directory already exist $G [REMOVING] $DEF"
-			echo "$G rm -rf $BUILD_DIR/$PROGRAM-BUILD $DEF"
-			rm -rf $BUILD_DIR/$PROGRAM-BUILD
-		else
-			echo "$M.$DEF"
+	if [ -d $BUILD_DIR/$PROGRAM-BUILD ]; then
+	  echo "$C Build directory already exist $G [REMOVING] $DEF"
+	  echo "$G rm -rf $BUILD_DIR/$PROGRAM-BUILD $DEF"
+	  rm -rf $BUILD_DIR/$PROGRAM-BUILD
+	else
+	  echo "$M.$DEF"
 	fi
 
 	echo "$C Making directory for separate build $DEF"
 	echo "$G mkdir $BUILD_DIR/$PROGRAM-BUILD $DEF"
 	mkdir $BUILD_DIR/$PROGRAM-BUILD
 }
-export -f unpackGzipSep
+export -f SepBuild
 
-#Function unpacking archive and make directory for separete build
-unpackBzipSep (){
-	echo "$Y Starting build script $PROGRAM $DEF";
-
-	if [ -d $BUILD_DIR/$PROGRAM ];
-		then
-			echo "$C Directory with source already exist $G [REMOVING] $DEF"
-			echo "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
-			rm -rf $BUILD_DIR/$PROGRAM
-			echo "$C Source direcotry $G [UNPACKING] $DEF"
-			echo "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
-			tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
-		else
-			echo "$C Source direcotry $G [UNPACKING] $DEF"
-			echo "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
-			tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
-	fi
-
-	if [ -d $BUILD_DIR/$PROGRAM-BUILD ];
-		then
-			echo "$C Build directory already exist $G [REMOVING] $DEF"
-			echo "$G rm -rf $BUILD_DIR/$PROGRAM-BUILD $DEF"
-			rm -rf $BUILD_DIR/$PROGRAM-BUILD
-		else
-			echo "$M.$DEF"
-	fi
-
-	echo "$C Making directory for separate build $DEF"
-	echo "$G mkdir $BUILD_DIR/$PROGRAM-BUILD $DEF"
-	mkdir $BUILD_DIR/$PROGRAM-BUILD
+#test if existing directory for mpfr gmp mpc
+gccSupProgTest(){
+  if [ -d $BUILD_DIR/$PROGRAM ]; then
+    echo -e "$C Directory with source already exist $G [REMOVING] $DEF"
+    echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
+    rm -rf $BUILD_DIR/$PROGRAM
+  else
+    echo -e "$M.$DEF"
+  fi
+  if [ -d $BUILD_DIR/$NAME ]; then
+      echo -e "$C Directory with source already exist $G [REMOVING] $DEF"
+      echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
+      rm -rf $BUILD_DIR/$NAME
+    else
+      echo -e "$M.$DEF"
+  fi
 }
-export -f unpackBzipSep
+export -f gccSupProgTest
 
 #function testing if directory exist if not make directory
 #parameter= directory
 testExDir (){
-	if [ -d $1 ];
-		then
-			echo "$C Directory $1 exist"
-		else
-			echo "$C Directory $1 not exist $DEF"
-			echo "$G mkdir -p $1 $DEF"
-			mkdir -p $1
+	if [ -d $1 ]; then
+	  echo "$C Directory $1 exist"
+	else
+	  echo "$C Directory $1 not exist $DEF"
+	  echo "$G mkdir -p $1 $DEF"
+	  mkdir -p $1
 	fi
 }
 export -f testExDir
@@ -140,14 +122,13 @@ export -f testExDir
 #third=destination dir
 #example: testSimLink /home/user/LFS /home/user/test/LFS /home/user/
 testSimLink (){ 
-	if [ -L $1 ];
-		then
-			echo "$C Symbolic link $1 exist $DEF"
-		else
-			echo "$C Symbolic link $G $1 $C not exist $DEF"
-			echo "Making symbolic link $G $1 $DEF"
-			echo "$G ln -s $2 $3 $DEF"
-			ln -s $2 $3
+	if [ -L $1 ]; then
+	  echo "$C Symbolic link $1 exist $DEF"
+	else
+	  echo "$C Symbolic link $G $1 $C not exist $DEF"
+	  echo "Making symbolic link $G $1 $DEF"
+	  echo "$G ln -s $2 $3 $DEF"
+	  ln -s $2 $3
 	fi
 }
 export -f testSimLink
@@ -202,11 +183,10 @@ export -f c_Make
 c_MakeTest (){
 	echo "for start make $@ pres 1 and enter"
 	read var
-		if [ $var == 1 ];
-	    	then
-				echo -e "$G make $@ $DEF"
-				make $@
-		fi
+	if [ $var == 1 ]; then
+	  echo -e "$G make $@ $DEF"
+	  make $@
+	fi
 }
 export -f c_MakeTest
 
@@ -261,20 +241,39 @@ export -f copyFilesRec
 compareFiles (){
 if cmp $1 $2 &> /dev/null
 	then
-		echo "$C . $DEF"
+	  echo "$C Files are matching [OK] $DEF"
 	else
-		echo "$R Linker test [FAIL] $DEF"
-		exit 1
+	  echo "$R Linker test [FAIL] $DEF"
+	  exit 1
     fi
 }
 export -f compareFiles
 
 #function wait for user interaction
 waitUser (){
-	if [ $WAIT == 1 ];
-    	then
-		echo "for continue pres enter"
-		read > /dev/null
-	fi
+  if [ $WAIT == 1 ]; then
+    echo "for continue pres enter"
+    read > /dev/null
+  fi
 }
 export -f waitUser
+
+#function downloaded file given in first parametr
+download (){
+ wget -c ${1} -P ${SOURCES_DIR}/
+}
+
+export -f download
+
+#function compare md5 sums
+#it checked file given in first variable
+#then compare with md5sum given in second variable
+check(){
+  echo "$C Checking md5 checksum for file ${1} $DEF"
+  md5test=$(md5sum $SOURCES_DIR/${1} | awk '{ print $1 }')
+  if [ ${2} == ${md5test} ]; then
+    echo "$G [OK] $DEF";
+  else
+    echo "$R [FAIL] $DEF";
+  fi
+}
